# SQLite version 3.x
#   gem install postgresql
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'postgresql'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: kmplr_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: kmplr_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kmplr_production
  pool: 5
  timeout: 5000
